### ISSUE TITLE
Address not valid during read

### ISSUE THREAD

**Issue by bvitaz-ck** [alliedvision/VmbPy#1]
I am using the camera Alvium 1800 U-319. I have installed the VimbaX SDK (`VimbaX_Setup-2022-1-Win64.exe`), and installed VmbPy v1.0.1 in a new Python 3.11 virtual environment (`pip install https://github.com/alliedvision/VmbPy/releases/download/1.0.1/vmbpy-1.0.1-py3-none-any.whl`). I have tried some of the example files with no success, always getting the error `FeatureEnumRange GenICam::RuntimeException: Address not valid during read (address=-1342109900; length=4)`.

To demonstrate the issue, I have created a basic script to get all of the cameras and print their IDs, then tries to access the first camera context:
```python
import vmbpy

if __name__ == '__main__':
    vmb = vmbpy.VmbSystem.get_instance()
    with vmb:
        cams = vmb.get_all_cameras()
        for cam in cams:
            print(cam)
        with cams[0] as cam:
            print(cam)
```
This outputs the following:
```
Camera(id=DEV_1AB22C0235C2)
03-29-2023 15:34:49.461 [T] FeatureEnumRange GenICam::RuntimeException: Address not valid during read (address=-1342109900; length=4)
Traceback (most recent call last):
  File "D:\Development\Assembler\vmbpy-test\main.py", line 9, in <module>
    with cams[0] as cam:
  File "C:\Users\bvitaz\.virtualenvs\vmbpy-test--FxYl47t\lib\site-packages\vmbpy\util\tracer.py", line 134, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\bvitaz\.virtualenvs\vmbpy-test--FxYl47t\lib\site-packages\vmbpy\camera.py", line 106, in __enter__
    self._open()
  File "C:\Users\bvitaz\.virtualenvs\vmbpy-test--FxYl47t\lib\site-packages\vmbpy\util\tracer.py", line 134, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\bvitaz\.virtualenvs\vmbpy-test--FxYl47t\lib\site-packages\vmbpy\util\context_decorator.py", line 44, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\bvitaz\.virtualenvs\vmbpy-test--FxYl47t\lib\site-packages\vmbpy\camera.py", line 517, in _open
    self._attach_feature_accessors()
  File "C:\Users\bvitaz\.virtualenvs\vmbpy-test--FxYl47t\lib\site-packages\vmbpy\util\tracer.py", line 134, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\bvitaz\.virtualenvs\vmbpy-test--FxYl47t\lib\site-packages\vmbpy\featurecontainer.py", line 64, in _attach_feature_accessors
    self._feats = discover_features(self._handle)
  File "C:\Users\bvitaz\.virtualenvs\vmbpy-test--FxYl47t\lib\site-packages\vmbpy\util\tracer.py", line 134, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\bvitaz\.virtualenvs\vmbpy-test--FxYl47t\lib\site-packages\vmbpy\feature.py", line 1209, in discover_features
    result.append(_build_feature(handle, info))
  File "C:\Users\bvitaz\.virtualenvs\vmbpy-test--FxYl47t\lib\site-packages\vmbpy\feature.py", line 1174, in _build_feature
    feat = EnumFeature(handle, info)
  File "C:\Users\bvitaz\.virtualenvs\vmbpy-test--FxYl47t\lib\site-packages\vmbpy\util\tracer.py", line 134, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\bvitaz\.virtualenvs\vmbpy-test--FxYl47t\lib\site-packages\vmbpy\feature.py", line 489, in __init__
    self.__entries: EnumEntryTuple = _discover_enum_entries(self._handle, self._info.name)
  File "C:\Users\bvitaz\.virtualenvs\vmbpy-test--FxYl47t\lib\site-packages\vmbpy\util\tracer.py", line 134, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\bvitaz\.virtualenvs\vmbpy-test--FxYl47t\lib\site-packages\vmbpy\feature.py", line 594, in _discover_enum_entries
    call_vmb_c('VmbFeatureEnumRangeQuery', handle, feat_name, None, 0, byref(enums_count))
  File "C:\Users\bvitaz\.virtualenvs\vmbpy-test--FxYl47t\lib\site-packages\vmbpy\util\tracer.py", line 134, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\bvitaz\.virtualenvs\vmbpy-test--FxYl47t\lib\site-packages\vmbpy\c_binding\vmb_c.py", line 891, in call_vmb_c
    getattr(_lib_instance, func_name)(*args)
  File "C:\Users\bvitaz\.virtualenvs\vmbpy-test--FxYl47t\lib\site-packages\vmbpy\c_binding\vmb_c.py", line 815, in _eval_vmberror
    raise VmbCError(result)
vmbpy.c_binding.vmb_common.VmbCError: VmbCError(<VmbError.InternalFault: -1>)

Process finished with exit code 1
```

VmbViewer can connect to the camera and shows images as expected.

How can I get past this error?

**Comment by bvitaz-ck** [comment]
Apparently the camera firmware was out of date and updating it fixed the problem.
