### ISSUE TITLE
RuntimeException: Address not valid during read

### ISSUE THREAD

**Issue by koltonha** [alliedvision/VmbPy#14]
I cannot run most of the Python examples on an ARM64 system (Nvidia Xavier AGX).
It seems to go wrong when the camera is opened.
✓The list-cameras example works.
✓The VimbaXViewer works.
But that's about it.
There are two USB3 alliedvision cameras in my system, both inserted into a USB3 port.
Any idea what could be the problem? Thanks in advance!

Output of the synchronous grab example below:

```
/////////////////////////////////////
/// VmbPy Synchronous Grab Example ///
//////////////////////////////////////


08-29-2023 16:53:55.600 [T] FeatureEnumRange GenICam::RuntimeException: Address not valid during read (address=-1342109900; length=4)
Traceback (most recent call last):
  File "api/examples/VmbPy/synchronous_grab.py", line 117, in <module>
    main()
  File "api/examples/VmbPy/synchronous_grab.py", line 108, in main
    with get_camera(cam_id) as cam:
  File "/kh-config/@conda-install/lib/python3.8/site-packages/vmbpy/util/tracer.py", line 131, in wrapper
    result = func(*args, **kwargs)
  File "/kh-config/@conda-install/lib/python3.8/site-packages/vmbpy/camera.py", line 106, in __enter__
    self._open()
  File "/kh-config/@conda-install/lib/python3.8/site-packages/vmbpy/util/tracer.py", line 131, in wrapper
    result = func(*args, **kwargs)
  File "/kh-config/@conda-install/lib/python3.8/site-packages/vmbpy/util/context_decorator.py", line 44, in wrapper
    return func(*args, **kwargs)
  File "/kh-config/@conda-install/lib/python3.8/site-packages/vmbpy/camera.py", line 517, in _open
    self._attach_feature_accessors()
  File "/kh-config/@conda-install/lib/python3.8/site-packages/vmbpy/util/tracer.py", line 131, in wrapper
    result = func(*args, **kwargs)
  File "/kh-config/@conda-install/lib/python3.8/site-packages/vmbpy/featurecontainer.py", line 64, in _attach_feature_accessors
    self._feats = discover_features(self._handle)
  File "/kh-config/@conda-install/lib/python3.8/site-packages/vmbpy/util/tracer.py", line 131, in wrapper
    result = func(*args, **kwargs)
  File "/kh-config/@conda-install/lib/python3.8/site-packages/vmbpy/feature.py", line 1209, in discover_features
    result.append(_build_feature(handle, info))
  File "/kh-config/@conda-install/lib/python3.8/site-packages/vmbpy/feature.py", line 1174, in _build_feature
    feat = EnumFeature(handle, info)
  File "/kh-config/@conda-install/lib/python3.8/site-packages/vmbpy/util/tracer.py", line 131, in wrapper
    result = func(*args, **kwargs)
  File "/kh-config/@conda-install/lib/python3.8/site-packages/vmbpy/feature.py", line 489, in __init__
    self.__entries: EnumEntryTuple = _discover_enum_entries(self._handle, self._info.name)
  File "/kh-config/@conda-install/lib/python3.8/site-packages/vmbpy/util/tracer.py", line 131, in wrapper
    result = func(*args, **kwargs)
  File "/kh-config/@conda-install/lib/python3.8/site-packages/vmbpy/feature.py", line 594, in _discover_enum_entries
    call_vmb_c('VmbFeatureEnumRangeQuery', handle, feat_name, None, 0, byref(enums_count))
  File "/kh-config/@conda-install/lib/python3.8/site-packages/vmbpy/util/tracer.py", line 131, in wrapper
    result = func(*args, **kwargs)
  File "/kh-config/@conda-install/lib/python3.8/site-packages/vmbpy/c_binding/vmb_c.py", line 891, in call_vmb_c
    getattr(_lib_instance, func_name)(*args)
  File "/kh-config/@conda-install/lib/python3.8/site-packages/vmbpy/c_binding/vmb_c.py", line 815, in _eval_vmberror
    raise VmbCError(result)
vmbpy.c_binding.vmb_common.VmbCError: VmbCError(<VmbError.InternalFault: -1>)
```

Output of list-cameras example:
```
/////////////////////////////////
/// VmbPy List Cameras Example ///
//////////////////////////////////


Cameras found: 2
/// Camera Name   : Allied Vision 1800 U-811c
/// Model Name    : 1800 U-811c
/// Camera ID     : DEV_1AB22C0251AF
/// Serial Number : 0399R
/// Interface ID  : VimbaUSBInterface_0x0

/// Camera Name   : Allied Vision 1800 U-1240c
/// Model Name    : 1800 U-1240c
/// Camera ID     : DEV_1AB22C0287FB
/// Serial Number : 03JZV
/// Interface ID  : VimbaUSBInterface_0x0
```

Machine: Nvidia Xavier AGX
Cameras: two AlliedVision USB3 cameras
Kernel: Linux 5.10.104-tegra #1 SMP PREEMPT Wed Aug 10 20:17:07 PDT 2022 aarch64 aarch64 aarch64 GNU/Linux
Version: vmbpy-1.0.2-py3-none-any

**Comment by nordeh** [comment]
Please check the camera firmware version and update to 00.12.00.00611a22 if necessary:
https://cdn.alliedvision.com/fileadmin/content/software/firmware/USB/Alvium_U3V_Camera_00.12.00.00611a22.zip
