### ISSUE TITLE
vmbpy.c_binding.vmb_common.VmbCError: VmbCError(<VmbError.RetriesExceeded: -40>)

### ISSUE THREAD

**Issue by HarshitaKanamadi** [alliedvision/VmbPy#18]
Traceback (most recent call last):
  File "/app/vimba_client.py", line 75, in _start
    CameraConfigurator.setup(camera, calibration)
  File "/app/camera_configurator.py", line 32, in setup
    camera.load_settings(settings_file, PersistType.All)
  File "/opt/venv/lib/python3.10/site-packages/vmbpy/util/context_decorator.py", line 101, in wrapper
    return func(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/vmbpy/util/runtime_type_check.py", line 58, in wrapper
    return func(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/vmbpy/featurecontainer.py", line 207, in load_settings
    call_vmb_c('VmbSettingsLoad',
  File "/opt/venv/lib/python3.10/site-packages/vmbpy/util/tracer.py", line 131, in wrapper
    result = func(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/vmbpy/c_binding/vmb_c.py", line 891, in call_vmb_c
    getattr(_lib_instance, func_name)(*args)
  File "/opt/venv/lib/python3.10/site-packages/vmbpy/c_binding/vmb_c.py", line 815, in _eval_vmberror
    raise VmbCError(result)
vmbpy.c_binding.vmb_common.VmbCError: VmbCError(<VmbError.RetriesExceeded: -40>)
I am getting this error when i try to load an xml setting file of a camera. When i compared with other setting files, there is no difference i found. I want to know why i am facing this error.

**Comment by Teresa-AlliedVision** [comment]
From the xml files: You have two different cameras (for simplicity, camera A and camera B).
Are you trying to save the xml file of camera A into camera B?

If yes, this will fail in VimbaX, due camera specific features in the XML file. You can either change these features in the xml file, to make it fit the other camera or you can use Vimba6, where the xml file is a bit different and ignores the camera specific IDs.

For the first workaround, you need to change the following feature values to match the camera and specify the MAC ID of the other camera:

```xml
<CameraInfo Id="DEV_000F310380C3" Model="GT6400C (02-2701D)">
<Feature Name="DeviceDisplayName" Value="Allied Vision Technologies GT6400C (02-2701D) (DEV_000F310380C3)" Type="String" />
<Feature Name="DeviceID" Value="DEV_000F310380C3" Type="String" />
<Feature Name="StreamID" Value="DEV_000F310380C3-Stream-000" Type="String" />
<Stream Id="DEV_000F310380C3-Stream-000">
<Feature Name="StreamID" Value="DEV_000F310380C3-Stream-000" Type="String" />
```

**Comment by HarshitaKanamadi** [comment]
No i am not saving the xml files from camera A into camera B. The files i have attached are completely different xml files not related to each other. 
1) First file is the ones which dosent work "000F310380BF"(Camera A) is throwing vmbpy.c_binding.vmb_common.VmbCError: VmbCError(<VmbError.RetriesExceeded: -40>)
2) Second file "000F310380C3"(Camera B) is the one which works fine without error. I had used this file to compare with the first one.

**Comment by Teresa-AlliedVision** [comment]
Alright, that is very different. Are there XML files saved from Camera A that can be loaded into Camera A or does it fail with all XML files? I don't see anydifference in the XML files themselves, that would allow one to load and the other not.

Both cameras have Firmware 00.01.54.26872, but there is a newer version available.
I would suggest the following troubleshooting steps:

1. Update the firmware for both cameras: [Firmware Downloads](https://www.alliedvision.com/en/support/firmware-downloads/)
2. Try Vimba 6: [Vimba Download Page](https://www.alliedvision.com/en/products/vimba-sdk/#c1497)
3. Check your hardware connections. Do both cameras stream equally well at the max possible StreamBytesPerSecond or is one significantly worse? Check Stream -> Statistics in the Viewer to monitor package errors and resends.
