### ISSUE TITLE
vmbpy.error.VmbSystemError: Encountered an error during VmbStartup

### ISSUE THREAD

**Issue by niteshsd** [alliedvision/VmbPy#19]
2023-11-29 04:28:47,152 ERROR [vimba_client.py:116] VimbaCapture: Failed to start camera 192.168.9.74/aal-b9701u1-cam006 Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/vmbpy/vmbsystem.py", line 451, in _startup
    call_vmb_c('VmbStartup', _as_vmb_file_path(self.__path_configuration))
  File "/opt/venv/lib/python3.10/site-packages/vmbpy/util/tracer.py", line 131, in wrapper
    result = func(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/vmbpy/c_binding/vmb_c.py", line 891, in call_vmb_c
    getattr(_lib_instance, func_name)(*args)
  File "/opt/venv/lib/python3.10/site-packages/vmbpy/c_binding/vmb_c.py", line 815, in _eval_vmberror
    raise VmbCError(result)
vmbpy.c_binding.vmb_common.VmbCError: VmbCError(<VmbError.Already: -33>)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/vimba_client.py", line 110, in start
    self._start(frame_handler, calibration)
  File "/app/retry_mechanism.py", line 30, in wrapper
    return func(*args, **kwargs)
  File "/app/vimba_client.py", line 72, in _start
    with self._vimba:
  File "/opt/venv/lib/python3.10/site-packages/vmbpy/util/tracer.py", line 131, in wrapper
    result = func(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/vmbpy/vmbsystem.py", line 86, in __enter__
    self._startup()
  File "/opt/venv/lib/python3.10/site-packages/vmbpy/util/tracer.py", line 131, in wrapper
    result = func(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/vmbpy/util/context_decorator.py", line 44, in wrapper
    return func(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/vmbpy/vmbsystem.py", line 462, in _startup
    raise Exc(msg) from e
vmbpy.error.VmbSystemError: Encountered an error during VmbStartup

Camera Model - GT6400C
Firmware - Prosilica
VimbaX version - 1.0.2
 getting above VmbStartup error due to which sometimes the camera is not starting, what will be the reason and its solution?

**Comment by Teresa-AlliedVision** [comment]
This is unfortunately not enough for me to diagnose the issue, we would need your code and network topology (i.e. how many cameras are connected to the PC how exactly, are there switches involved, what model of network card you are using, etc.).
If this is the same camera, where the loading of the XML file fails, please contact support. 
[Contact Form for Support and Repair](https://www.alliedvision.com/en/about-us/contact-us/technical-support-repair-/-rma/)
Prosilica is the name of the camera line, so it gives no information on the firmware version. There is a feature called DeviceFirmwareVersion, please use that to check what firmware the camera is on.
