### ISSUE TITLE
Unable to import VmbPy (Invalid VmbC Version)

### ISSUE THREAD

**Issue by kentonkwoklo** [alliedvision/VmbPy#42]
Hello! I am unable to access the python sdk unfortunately. 

I have downloaded VimbaX via (https://www.alliedvision.com/en/products/software/vimba-x-sdk/) 
`VimbaX_Setup-2023-4-macOS.dmg`

and `vmbpy-1.0.5-py3-none-any.whl` via the releases site
```
python
>>> import vmbpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kenton/venvs/venv/lib/python3.12/site-packages/vmbpy/__init__.py", line 119, in <module>
    from .camera import AccessMode, Camera, CameraChangeHandler, CameraEvent
  File "/Users/kenton/venvs/venv/lib/python3.12/site-packages/vmbpy/camera.py", line 32, in <module>
    from .c_binding import (AccessMode, VmbCameraInfo, VmbCError, VmbError, VmbHandle, byref,
  File "/Users/kenton/venvs/venv/lib/python3.12/site-packages/vmbpy/c_binding/__init__.py", line 119, in <module>
    from .vmb_c import (EXPECTED_VMB_C_VERSION, G_VMB_C_HANDLE, VMB_C_VERSION, VmbAccessMode,
  File "/Users/kenton/venvs/venv/lib/python3.12/site-packages/vmbpy/c_binding/vmb_c.py", line 829, in <module>
    _lib_instance = _check_version(_attach_signatures(_lib_instance))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kenton/venvs/venv/lib/python3.12/site-packages/vmbpy/c_binding/vmb_c.py", line 819, in _check_version
    raise VmbSystemError(msg.format(EXPECTED_VMB_C_VERSION, VMB_C_VERSION))
vmbpy.error.VmbSystemError: Invalid VmbC Version: Expected: 1.0.6, Found:1.0.5
```

Thank you for your help.

**Comment by Teresa-AlliedVision** [comment]
Hi, there shoud be a vmbpy version that is part of the MacOS release. The current vmbpy API has been released with the new Windows and Linux APIs, that also updated the Python API. So the newest Python API needs a newer version of the VmbC binding than is available with the MacOS release.
